# base image
#################### Old file ###############
#FROM node:10.15
#############################################

#############################################
############### New file ####################
#############################################
FROM node:12-alpine 
#FROM mhart/alpine-node:11

# set working directory
RUN mkdir /app
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli

# add app
COPY . /app
# start app
CMD ng serve --host 0.0.0.0 --disable-host-check
